services:
  migrate:
    image: ${IVIDA_IMAGE_PREFIX}-api:${IVIDA_IMAGE_TAG}
    build: null
  api:
    image: ${IVIDA_IMAGE_PREFIX}-api:${IVIDA_IMAGE_TAG}
    build: null
  worker:
    image: ${IVIDA_IMAGE_PREFIX}-worker:${IVIDA_IMAGE_TAG}
    build: null
  frontend:
    image: ${IVIDA_IMAGE_PREFIX}-frontend:${IVIDA_IMAGE_TAG}
    build: null
